CREATE TABLE IF NOT EXISTS `audit` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `request_id` VARCHAR(64) DEFAULT NULL COMMENT '请求ID',
  `operation_id` VARCHAR(64) DEFAULT NULL COMMENT '操作人',
  `operation_alias` VARCHAR(128) DEFAULT NULL COMMENT '操作人别名',
  `action` VARCHAR(64) DEFAULT NULL COMMENT '操作行为',
  `module` VARCHAR(64) DEFAULT NULL COMMENT '操作模块',
  `operation_params` TEXT DEFAULT NULL COMMENT '操作参数',
  `operation_result` TEXT DEFAULT NULL COMMENT '操作结果',
  `status` TINYINT DEFAULT 1 COMMENT '操作状态：1成功 0失败',
  `error_msg` TEXT DEFAULT NULL COMMENT '错误信息',
  `ip_address` VARCHAR(64) DEFAULT NULL COMMENT '操作IP',
  `user_agent` VARCHAR(512) DEFAULT NULL COMMENT '用户代理',
  `cost_time` BIGINT DEFAULT 0 COMMENT '耗时(毫秒)',
  `organization_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
  `update_by` BIGINT DEFAULT NULL COMMENT '修改人',
  `is_deleted` TINYINT DEFAULT 0 COMMENT '逻辑删除 0-否 1-是',
  PRIMARY KEY (`id`),
  KEY `idx_request_id` (`request_id`),
  KEY `idx_operation_id` (`operation_id`),
  KEY `idx_module` (`module`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_organization_id` (`organization_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
